In [23]:
#matrix 
from numpy import *

str1 = "2 3 1;4 5 9;6 7 0"
mat = np.matrix(str1)
print(mat)
d = np.diagonal(mat)
# print(d)
# print(mat.sum())
# print(d.min())
# print(d.max())
# print(matrix(arange(12).reshape(3,4)))
# print(type(d))
# print(mat.prod(0))
# print(mat.prod(1))
#print(sort(mat))
print(sort(mat,axis=0))
print(sort(mat,axis=1))
print(sort(mat))
print(sort(-mat))
print(-sort(-mat))

[[2 3 1]
 [4 5 9]
 [6 7 0]]
[[2 3 0]
 [4 5 1]
 [6 7 9]]
[[1 2 3]
 [4 5 9]
 [0 6 7]]
[[1 2 3]
 [4 5 9]
 [0 6 7]]
[[-3 -2 -1]
 [-9 -5 -4]
 [-7 -6  0]]
[[3 2 1]
 [9 5 4]
 [7 6 0]]
